export const actions = {
    ADD_ITEM: {
        REQUEST: 'ADD_ITEM_REQUEST',
        SUCCESS: 'ADD_ITEM_SUCCESS',
        FAILED: 'ADD_ITEM_FAILED'
    },
    GET_TODOS: {
        REQUEST: 'GET_TODOS_REQUEST',
        SUCCESS: 'GET_TODOS_SUCCESS',
        FAILED: 'GET_TODOS_FAILED'
    },
    REMOVE_TODOS: {
        REQUEST: 'REMOVE_TODOS_REQUEST',
        SUCCESS: 'REMOVE_TODOS_SUCCESS',
        FAILED: 'REMOVE_TODOS_FAILED'
    },
    CHECKBOX_HANDLER: {
        REQUEST: 'CHECKBOX_HANDLER_REQUEST',
        SUCCESS: 'CHECKBOX_HANDLER_SUCCESS',
        FAILED: 'CHECKBOX_HANDLER_FAILED'
    },
    DELETE_COMPLETED: {
        REQUEST: 'DELETE_COMPLETED_REQUEST',
        SUCCESS: 'DELETE_COMPLETED_SUCCESS',
        FAILED: 'DELETE_COMPLETED_FAILED'
    },
    TOGGLE_ALL: {
        REQUEST: 'TOGGLE_ALL_REQUEST',
        SUCCESS: 'TOGGLE_ALL_SUCCESS',
        FAILED: 'TOGGLE_ALL_FAILED'
    },
    EDIT_TODO: {
        REQUEST: 'EDIT_TODO_REQUEST',
        SUCCESS: 'EDIT_TODO_SUCCESS',
        FAILED: 'EDIT_ALL_FAILED'
    },
    SET_TYPE: 'SET_TYPE',
};